config/routes.rb
Rails.application.routes.draw do
  root "employees#index"

  resources :employees, only: %i[index show]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :start_fetcher

  def index
    @employees = @employee_fetcher.page(page_params).all
    @current_page = page_params.to_i
    @total_pages = @employee_fetcher.total_pages
  end

  def show
    @employee = @employee_fetcher.find(params[:id])
  end

  private

  def start_fetcher
    @employee_fetcher = Reqres::EmployeeFetcher.new
  end

  def page_params
    params[:page] ? params.require(:page) : 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/index.html.erb
<div>
  <h2>Employees</h2>
  <table class="table card is-hoverable">
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <th>
            <%= link_to employee_path(employee.id), class: "w-100 is-flex is-align-items-center" do %>
              <figure class="image is-48x48 ml-0 mr-5 my-0 is-flex is-align-items-center">
                <%= image_tag(employee.avatar, class: "is-rounded") %>
              </figure>
              <div class="columns w-100">
                <span class="mt-3 tag is-success is-light">Online</span>
                <span class="column is-2 has-text-black"><%= "#{employee.first_name} #{employee.last_name}" %></span>
                <span class="column is-2 has-text-weight-normal"><%= employee.email %></span>
                <div class="column has-text-grey has-text-weight-semibold is-flex is-align-items-center is-justify-content-end pr-5 visible-when-hovering">
                  <span>Visit profile</span>
                  <%= image_tag("go-to.svg", width: 18, class: "ml-2") %>
                </div>
              </div>

            <% end %>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br/>

  <div class="pb-5 has-text-centered">
    <p class="is-size-7 has-text-weight-semibold has-text-grey-light">CURRENT PAGE</p>
    <% (1..@total_pages).each do |page| %>
      <%= link_to employees_path(page:), class: "button is-small is-black #{'is-outlined' if @current_page != page}" do %>
        <%= page %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/employees/show.html.erb
<%= link_to :back, class: "has-text-grey has-text-weight-semibold is-flex is-align-items-center mb-5" do %>
  <%= image_tag("go-to.svg", width: 18, class: "mr-2 flip") %>
  Go back
<% end %>

<div class="card p-5">
  <div class="is-flex">
    <figure class="image is-128x128 ml-0 mr-5 my-0">
      <%= image_tag(@employee.avatar, class: "is-rounded-small") %>
    </figure>
    <div class="mt-4">
      <div class="is-flex is-align-items-center mb-2">
        <h2 class="m-0"><%= "#{@employee.first_name} #{@employee.last_name}" %></h2>
        <span class="tag is-success is-light has-text-weight-semibold ml-2 mt-1">Online</span>
      </div>
      <h6 class="has-text-grey-light mb-2">Ruby on Rails Developer</h6>
      <p class="has-text-weight-normal is-size-6"><%= @employee.email %></p>
    </div>
  </div>

  <hr/>

  <div class="columns">
    <div class="column pr-5 mr-5 br-2 has-text-justified">
      <h4>Bio</h4>
      <p><%= Faker::Lorem.paragraph_by_chars(number: 512, supplemental: false) %></p>
    </div>

    <div class="column">
      <h4>Highlights</h4>
      <ul>
        <li><%= Faker::Lorem.sentence(word_count: 3) %></li>
        <li><%= Faker::Lorem.sentence(word_count: 3) %></li>
        <li><%= Faker::Lorem.sentence(word_count: 3) %></li>
        <li><%= Faker::Lorem.sentence(word_count: 3) %></li>
      </ul>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeDirectory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="has-background-light">
    <%= render "shared/navbar" %>
    <div class="content container pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-menu container">
    <div class="navbar-start">
      <%= link_to "Our team", employees_path, class: "navbar-item" %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item pr-0">
          <a href="https://github.com/bigchickenwings" target="_blank" class="p-2 mr-2">
            <%= image_tag("github.svg") %>
          </a>
          <a href="https://www.linkedin.com/in/fernandorpm/" target="_blank" class="p-2">
            <%= image_tag("linkedin.svg") %>
          </a>
      </div>
    </div>

  </div>
</nav>